--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/davidlouis101/Clearinventory
build-by-default: true
branches:
- master
projects:
  Clearinventory:
    path: ""
    icon: Clearinv.png
...
