name: Clearinventory
main: Commands\Main
author: CrowBaldeYT
version: 1.1.6
api: 3.0.0
commands:
 clear:
   description: clear your inventory!
   aliases: ["clearinv", "ci"]
   usage: "/clear"
   permission: clear.cmd

 permission:
  clear.cmd:
   default: OP
