name: Clearinventory
main: Clearinventory\davidlouis101\ClearCommand
author: CrowBaldeYT
version: 1.1.7
api: 3.0.0
description: A Clearinventory plugin with Custom Messages
commands:
 clear:
   description: Clear your inventory!
   aliases: ["clearinv", "ci"]
   usage: "/clear"
   permission: clear.cmd
 discord:
   description: Discord Server
   aliases: ["dc", "DC"]

 permission:
  clear.cmd:
   default: OP
