name: Clearinventory
main: Clearinventory\davidlouis101\ClearCommand
author: CrowBaldeYT
version: 1.1.7
api: 3.0.0
description: A Clearinventory plugin with Custom Messages and Sounds
commands:
 clear:
   description: Clear your Inventory Completely
   aliases: ["clearinv", "ci"]
   usage: "/clear"
   permission: clear.cmd

   permission:
    clear.cmd:
      default: OP
